<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('clients')->insert([
            [
                'name' => 'Global Tech Solutions Inc.',
                'contact_person' => 'Mark Johnson',
                'email' => 'mark.johnson@globaltech.com',
                'phone' => '+1 (555) 010-2000',
                'address' => '123 Technology Drive, Suite 100',
                'city' => 'San Francisco',
                'state' => 'California',
                'postal_code' => '94102',
                'status' => 'active',
                'notes' => 'Leading technology solutions provider. Requires morning shift training.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Premier Business Consulting',
                'contact_person' => 'Lisa Anderson',
                'email' => 'lisa.anderson@pbc.com',
                'phone' => '+1 (555) 011-2001',
                'address' => '456 Executive Boulevard',
                'city' => 'New York',
                'state' => 'New York',
                'postal_code' => '10001',
                'status' => 'active',
                'notes' => 'Management consulting firm. Flexible scheduling available.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Innovation Digital Marketing',
                'contact_person' => 'Robert Chen',
                'email' => 'robert.chen@innovationdigital.com',
                'phone' => '+1 (555) 012-2002',
                'address' => '789 Creative Lane, Floor 5',
                'city' => 'Los Angeles',
                'state' => 'California',
                'postal_code' => '90001',
                'status' => 'active',
                'notes' => 'Digital marketing agency. Prefers afternoon sessions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Healthcare Innovations Group',
                'contact_person' => 'Dr. Patricia Williams',
                'email' => 'p.williams@healthcareinnovations.com',
                'phone' => '+1 (555) 013-2003',
                'address' => '321 Medical Center Road',
                'city' => 'Chicago',
                'state' => 'Illinois',
                'postal_code' => '60601',
                'status' => 'active',
                'notes' => 'Healthcare sector client. Compliance training required.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sustainable Energy Solutions',
                'contact_person' => 'James Mitchell',
                'email' => 'j.mitchell@sustainableenergy.com',
                'phone' => '+1 (555) 014-2004',
                'address' => '654 Green Street, Suite 200',
                'city' => 'Austin',
                'state' => 'Texas',
                'postal_code' => '78701',
                'status' => 'active',
                'notes' => 'Energy sector client. Safety training mandatory.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Financial Services International',
                'contact_person' => 'Amanda Scott',
                'email' => 'a.scott@fsibank.com',
                'phone' => '+1 (555) 015-2005',
                'address' => '987 Finance Plaza',
                'city' => 'Boston',
                'state' => 'Massachusetts',
                'postal_code' => '02101',
                'status' => 'active',
                'notes' => 'Banking sector. Requires compliance and security training.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Retail Excellence Network',
                'contact_person' => 'William Brown',
                'email' => 'w.brown@retailexcellence.com',
                'phone' => '+1 (555) 016-2006',
                'address' => '111 Shopping Center Boulevard',
                'city' => 'Miami',
                'state' => 'Florida',
                'postal_code' => '33101',
                'status' => 'active',
                'notes' => 'Large retail chain. Needs customer service training.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manufacturing Excellence Corp',
                'contact_person' => 'Thomas Garcia',
                'email' => 't.garcia@mfgexcellence.com',
                'phone' => '+1 (555) 017-2007',
                'address' => '222 Industrial Park Drive',
                'city' => 'Detroit',
                'state' => 'Michigan',
                'postal_code' => '48201',
                'status' => 'active',
                'notes' => 'Manufacturing company. Shift-based training schedule.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Educational Excellence Institute',
                'contact_person' => 'Dr. Susan Martinez',
                'email' => 's.martinez@educationalexcellence.edu',
                'phone' => '+1 (555) 018-2008',
                'address' => '333 University Road',
                'city' => 'Seattle',
                'state' => 'Washington',
                'postal_code' => '98101',
                'status' => 'active',
                'notes' => 'Educational institution. Faculty development focus.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hospitality & Tourism Services',
                'contact_person' => 'Maria Rodriguez',
                'email' => 'm.rodriguez@hospitalityservices.com',
                'phone' => '+1 (555) 019-2009',
                'address' => '444 Resort Drive, Suite 300',
                'city' => 'Las Vegas',
                'state' => 'Nevada',
                'postal_code' => '89101',
                'status' => 'active',
                'notes' => 'Hospitality group. Flexible evening scheduling available.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
