<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Admin User
        DB::table('users')->insert([
            [
                'employee_no' => 'EMP001',
                'firstname' => 'Admin',
                'middlename' => null,
                'lastname' => 'User',
                'email' => 'admin@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('admin123'),
                'phone' => '+1 (555) 001-1000',
                'avatar' => null,
                'department' => 'Administration',
                'position' => 'System Administrator',
                'user_type' => 'admin',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Instructors
            [
                'employee_no' => 'EMP002',
                'firstname' => 'John',
                'middlename' => 'Michael',
                'lastname' => 'Anderson',
                'email' => 'john.anderson@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'phone' => '+1 (555) 002-1001',
                'avatar' => null,
                'department' => 'Training & Development',
                'position' => 'Senior Instructor',
                'user_type' => 'instructor',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_no' => 'EMP003',
                'firstname' => 'Sarah',
                'middlename' => 'Elizabeth',
                'lastname' => 'Martinez',
                'email' => 'sarah.martinez@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'phone' => '+1 (555) 003-1002',
                'avatar' => null,
                'department' => 'Training & Development',
                'position' => 'Instructor',
                'user_type' => 'instructor',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_no' => 'EMP004',
                'firstname' => 'David',
                'middlename' => 'James',
                'lastname' => 'Thompson',
                'email' => 'david.thompson@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'phone' => '+1 (555) 004-1003',
                'avatar' => null,
                'department' => 'Operations',
                'position' => 'Instructor',
                'user_type' => 'instructor',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_no' => 'EMP005',
                'firstname' => 'Emma',
                'middlename' => 'Louise',
                'lastname' => 'Garcia',
                'email' => 'emma.garcia@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'phone' => '+1 (555) 005-1004',
                'avatar' => null,
                'department' => 'Sales & Marketing',
                'position' => 'Training Coordinator',
                'user_type' => 'instructor',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_no' => 'EMP006',
                'firstname' => 'Michael',
                'middlename' => 'Robert',
                'lastname' => 'Johnson',
                'email' => 'michael.johnson@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'phone' => '+1 (555) 006-1005',
                'avatar' => null,
                'department' => 'HR & Compliance',
                'position' => 'Instructor',
                'user_type' => 'instructor',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Office Staff
            [
                'employee_no' => 'EMP007',
                'firstname' => 'Rebecca',
                'middlename' => 'Anne',
                'lastname' => 'Williams',
                'email' => 'rebecca.williams@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'phone' => '+1 (555) 007-1006',
                'avatar' => null,
                'department' => 'Administration',
                'position' => 'Office Manager',
                'user_type' => 'office_staff',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_no' => 'EMP008',
                'firstname' => 'Christopher',
                'middlename' => 'Paul',
                'lastname' => 'Davis',
                'email' => 'christopher.davis@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'phone' => '+1 (555) 008-1007',
                'avatar' => null,
                'department' => 'IT Support',
                'position' => 'IT Administrator',
                'user_type' => 'office_staff',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'employee_no' => 'EMP009',
                'firstname' => 'Jennifer',
                'middlename' => 'Marie',
                'lastname' => 'Wilson',
                'email' => 'jennifer.wilson@caglobal.com',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'phone' => '+1 (555) 009-1008',
                'avatar' => null,
                'department' => 'Finance',
                'position' => 'Finance Officer',
                'user_type' => 'office_staff',
                'status' => 'active',
                'remember_token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
